### ISSUE TITLE
label:"help wanted" Compatibility With W5100

### ISSUE THREAD

**Issue by robbpaulsen** [cifertech/ARPoLAN#1]
# Hi,

I have a couple of `IDUINOS W5100`
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.todomicro.com.ar%2F3150-medium_default%2Farduino-ethernet-shield-w5100.jpg&f=1&nofb=1&ipt=a7c9d447f0fa27829c6a808ab74bc2424ed29de850a9c9f132ec18c7a10991a5&ipo=images) 

Ethernet Shields with SDcard's , I was actually looking for a project like this, but I've been on the search engines and there's not much information about the shield I have with the SDcard, by any chance do you know if it could be compatible or just switch libraries to get the project to compile or something? thanks in advance and lastly it would be awesome if you made a video on your YT channel.

**Comment by cifertech** [comment]
Hi @robbpaulsen 
I don't have any experience with the w5100, but I think it's better to first find the library for it, use the same logic in my code, and then create your scenario. However, I have to say that if you are open to changing the hardware, the w5500 is a good choice.

**Comment by robbpaulsen** [comment]
Thanks a lot for the comment back,

I'm not closed to the W5500, I just wanted to use those shields I've had them almost for a year but I guess it would be on another project,  let me hit aliexpress and pick a W5500, have nice day and again thanks for the follow up, I'll be marking the issue as resolved 👍🏻
